import allIcon from "./IconProvider";
import allImages from "./ImageProvider";

const {
  footerIcon,
  rightChev,
  folder,
  downChev,
  email,
  call,
  mDown,
  aboutPageIcon,
  techIcons,
} = allIcon;
const { myselfImage, snippetOne, snippetTwo, projectImages } = allImages;

const navbarArray = [
  {
    id: 1,
    name: "jhulon-kumar",
    className: "border-r ",
    status: true,
    responsive: false,
  },
  {
    id: 2,
    name: "_hello",
    className: "border-r",
    status: false,
    responsive: true,
    to: "/",
  },
  {
    id: 3,
    name: "_about-me",
    className: "",
    status: false,
    responsive: true,
    to: "/about-me",
  },
  {
    id: 4,
    name: "_projects",
    className: "border-r border-l",
    status: false,
    responsive: true,
    to: "/projects",
  },

  {
    id: 5,
    name: "_contact-me",
    className: "border-l",
    status: false,
    responsive: true,
    isLast: true,
    to: "/contact-me",
  },
];

const footerArray = [
  { id: 1, icon: "find me in:" },
  { id: 2, icon: footerIcon[0].icon },
  { id: 3, icon: footerIcon[1].icon },
];

const bio = [
  {
    id: 1,
    key: "bio",
    displayName: "bio",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "interests",
    displayName: "interests",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
  {
    id: 3,
    key: "education",
    displayName: "education",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-indigo_500",
    order: 3,
    isActive: true,
  },
  {
    id: 4,
    key: "high-school",
    displayName: "high School",
    icon2: mDown,
    order: 4,
    // isActive: true,
    className: "pl-4",
  },
  {
    id: 5,
    key: "diploma",
    displayName: "diploma",
    icon2: mDown,
    order: 5,
    // isActive: true,
    className: "pl-4",
  },
];

const professionalInfo = [
  {
    id: 1,
    key: "experience",
    displayName: "experience",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "hard-skills",
    displayName: "hard-skills",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
  {
    id: 3,
    key: "education",
    displayName: "soft-skills",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-indigo_500",
    order: 3,
    isActive: true,
  },
];

const hobbies = [
  {
    id: 1,
    key: "sports",
    displayName: "sports",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "favorite-games",
    displayName: "favorite-games",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
];

const contact = [
  {
    id: 1,
    key: "email",
    displayName: "user@gmail.com",
    icon: email,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "phone-number",
    displayName: "+8801854555136",
    icon: call,
    icon2Class: "text-rose_400",
    order: 2,
    isActive: true,
  },
];

const snippet = [
  {
    id: 1,
    userImage: myselfImage,
    userName: "@basudevkumer",
    to: "https://github.com/basudevkumer/e-commerce1.0/blob/main/src/api/productApiP.js",
    time: "3",
    details: "Details",
    star: "0",
    codeImage: snippetOne,
  },
  {
    id: 2,
    userImage: myselfImage,
    userName: "@basudevkumer",
    to: "https://github.com/basudevkumer/e-commerce1.0/blob/main/src/hooks/useCategory.jsx",
    time: "3",
    details: "Details",
    star: "0",
    codeImage: snippetTwo,
  },
];
const allProjects = [
  {
    id: 1,
    title: "Project 1 ",
    subtitle: "// cilcon ecommerce-site",
    image: projectImages[0].image,
    description: "this a e-commerce site....",
    technologies: [
      "React",
      "CSS",
      "Tailwind",
      "HTML",
      "tanstack",
      "tanstack-qerry",
      "swiper js",
      "redux",
      "firebase",
      "react-router",
      "JavaScript",
    ],
    to: "https://e-commerce1-0.vercel.app/",
  },
  {
    id: 2,
    title: "Project 2 ",
    subtitle: "// innovate-1 {animated site}",
    image: projectImages[1].image,
    description: "innovate-1 animate site...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "react-bootstrap",
      "animation",
      "keyfram",
      "JavaScript",
    ],
    to: "https://react-innovale-one.vercel.app/",
  },
  {
    id: 3,
    title: "Project 3 ",
    subtitle: "// innovate-2 {animated site}",
    image: projectImages[2].image,
    description: "innovate-2 animate site...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "react-bootstrap",
      "animation",
      "keyfram",
      "JavaScript",
    ],
    to: "https://innovale2.vercel.app/",
  },
  {
    id: 4,
    title: "Project 4 ",
    subtitle: "// blockchain landing site...",
    image: projectImages[9].image,
    description: "blockchain landing site...",
    technologies: ["HTML", "CSS", "tailwind", "tailwind-cli"],
    to: "https://blockchain-xi-henna.vercel.app/",
  },
  {
    id: 5,
    title: "Project 5 ",
    subtitle: "// innovate-4 landing page",
    image: projectImages[4].image,
    description: "innvate-4 landing page...",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "react",
      "react-slick",
      "tailwindcss",
      "react-router",
    ],
    to: "https://innovate5.vercel.app/",
  },
  {
    id: 6,
    title: "Project 6 ",
    subtitle: "// foodi landing page",
    image: projectImages[5].image,
    description: "foodi landing page...",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "swiper",
      "react-router",
      "tailwindcss",
      "react",
    ],
    to: "https://foodi-zeta-livid.vercel.app/",
  },
  {
    id: 7,
    title: "Project 7 ",
    subtitle: "// finsweet full site...",
    image: projectImages[6].image,
    description: "finsweet full site...",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "swiper",
      "react-router",
      "bootstrap",
      "react-bootstrap",
      "react-slick",
      "aos",
    ],
    to: "https://react-finsweet-two.vercel.app/",
  },
  {
    id: 8,
    title: "Project 8 ",
    subtitle: "// freshWebsite landing site...",
    image: projectImages[7].image,
    description: "freshWebsite landing site...",
    technologies: ["HTML", "CSS"],
    to: "https://basudevkumer.github.io/freshWebsite/",
  },
  {
    id: 9,
    title: "Project 9 ",
    subtitle: "// dzzling demo site...",
    image: projectImages[8].image,
    description: "Dazzling Demo site...",
    technologies: ["HTML", "CSS", "bootstrap"],
    to: "https://basudevkumer.github.io/Boot_Project_1/",
  },
  {
    id: 10,
    title: "Project 10 ",
    subtitle: "// innovate-3 landing page",
    image: projectImages[3].image,
    description: "innovate-3 langing page...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "daisyui",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innvate4.vercel.app/",
  },
  {
    id: 11,
    title: "Project 11 ",
    subtitle: "// innovate-5 landing page",
    image: projectImages[10].image,
    description: "innovate-5 langing page...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://github.com/basudevkumer/innovate5",
  },
  {
    id: 12,
    title: "Project 12 ",
    subtitle: "// innovate-6 landing page",
    image: projectImages[11].image,
    description: "innovate-6 langing page...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
      "motion",
      "flowbite-react",
    ],
    to: "https://innovate6.vercel.app/",
  },
  {
    id: 13,
    title: "Project 13 ",
    subtitle: "// innovate-7 landing page",
    image: projectImages[12].image,
    description: "innovate-7 langing page...",
    technologies: ["HTML", "CSS", "bootstrap"],
    to: "https://innovate7.vercel.app/",
  },
  {
    id: 14,
    title: "Project 14 ",
    subtitle: "// innovate-8 landing page",
    image: projectImages[13].image,
    description: "innovate-8 langing page...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innovate8-seven.vercel.app/",
  },
  {
    id: 15,
    title: "Project 15 ",
    subtitle: "// innovate-9 landing page",
    image: projectImages[14].image,
    description: "innovate-9 langing page...",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innovate9.vercel.app/",
  },
  {
    id: 16,
    title: "Project 16 ",
    subtitle: "// simple carocell project",
    image: projectImages[15].image,
    description: "imple carocell project",
    technologies: ["HTML", "CSS", "tailwind", "JavaScript"],
    to: "https://caurosel.vercel.app/",
  },
  {
    id: 17,
    title: "Project 17 ",
    subtitle: "// simple quiz project",
    image: projectImages[16].image,
    description: "simple quiz project",
    technologies: ["HTML", "CSS", "tailwind", "JavaScript"],
    to: "https://simple-quiz-app-qo7i.vercel.app/",
  },
  {
    id: 18,
    title: "Project 18 ",
    subtitle: "// toaster",
    image: projectImages[17].image,
    description: "toaster",
    technologies: ["HTML", "CSS", "bootstrap", "JavaScript"],
    to: "https://basudevkumer.github.io/Toast-js/",
  },
];

const allTechIcons = [
  {
    id: 1,
    name: "React",
    icon: techIcons[0].icon,
  },
  {
    id: 2,
    name: "HTML",
    icon: techIcons[1].icon,
  },

  { id: 3, name: "Tailwind", icon: techIcons[2].icon },
  {
    id: 4,
    name: "Bootstrap",
    icon: techIcons[3].icon,
  },
  { id: 5, name: "Javascript", icon: techIcons[4].icon },
  { id: 6, name: "Next js", icon: techIcons[5].icon },
  { id: 7, name: "Typescript", icon: techIcons[6].icon },
];

const aboutTitle = [
  { id: 1, icon: aboutPageIcon[0].icon, title: "professional-info" },
  { id: 2, icon: aboutPageIcon[1].icon, title: "personal-info" },
  { id: 3, icon: aboutPageIcon[2].icon, title: "hobbies-info" },
];

const aboutobj = [
  { id: 1, title: "personal-info" },
  { id: 2, title: "professional-info" },
  { id: 3, title: "hobbies" },
  { id: 4, title: "contacts" },
];

export {
  navbarArray,
  footerArray,
  bio,
  contact,
  snippet,
  professionalInfo,
  hobbies,
  aboutTitle,
  allProjects,
  allTechIcons,
  aboutobj,
};
