import allIcon from "./IconProvider";
import allImages from "./ImageProvider";

const {
  footerIcon,
  rightChev,
  folder,
  downChev,
  email,
  call,
  mDown,
  aboutPageIcon,
  techIcons,
} = allIcon;
const { myselfImage, snippetOne, snippetTwo, projectImages } = allImages;

const navbarArray = [
  {
    id: 1,
    name: "jhulon-kumar",
    className: "border-r ",
    status: true,
    responsive: false,
  },
  {
    id: 2,
    name: "_hello",
    className: "border-r",
    status: false,
    responsive: true,
    to: "/",
  },
  {
    id: 3,
    name: "_about-me",
    className: "",
    status: false,
    responsive: true,
    to: "/about-me",
  },
  {
    id: 4,
    name: "_projects",
    className: "border-r border-l",
    status: false,
    responsive: true,
    to: "/projects",
  },

  {
    id: 5,
    name: "_contact-me",
    className: "border-l",
    status: false,
    responsive: true,
    isLast: true,
    to: "/contact-me",
  },
];

const footerArray = [
  { id: 1, icon: "find me in:" },
  { id: 2, icon: footerIcon[0].icon },
  { id: 3, icon: footerIcon[1].icon },
];

const bio = [
  {
    id: 1,
    key: "bio",
    displayName: "bio",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "interests",
    displayName: "interests",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
  {
    id: 3,
    key: "education",
    displayName: "education",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-indigo_500",
    order: 3,
    isActive: true,
  },
  {
    id: 4,
    key: "high-school",
    displayName: "high School",
    icon2: mDown,
    order: 4,
    // isActive: true,
    className: "pl-4",
  },
  {
    id: 5,
    key: "diploma",
    displayName: "diploma",
    icon2: mDown,
    order: 5,
    // isActive: true,
    className: "pl-4",
  },
];

const professionalInfo = [
  {
    id: 1,
    key: "experience",
    displayName: "experience",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "hard-skills",
    displayName: "hard-skills",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
  {
    id: 3,
    key: "education",
    displayName: "soft-skills",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-indigo_500",
    order: 3,
    isActive: true,
  },
];

const hobbies = [
  {
    id: 1,
    key: "sports",
    displayName: "sports",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "favorite-games",
    displayName: "favorite-games",
    icon: rightChev,
    icon2: folder,
    icon3: downChev,
    icon2Class: "text-teal_400",
    order: 2,
    isActive: true,
  },
];

const contact = [
  {
    id: 1,
    key: "email",
    displayName: "user@gmail.com",
    icon: email,
    icon2Class: "text-rose_400",
    order: 1,
    isActive: true,
  },
  {
    id: 2,
    key: "phone-number",
    displayName: "+8801854555136",
    icon: call,
    icon2Class: "text-rose_400",
    order: 2,
    isActive: true,
  },
];

const snippet = [
  {
    id: 1,
    userImage: myselfImage,
    userName: "@basudevkumer",
    to: "https://github.com/basudevkumer/e-commerce1.0/blob/main/src/api/productApiP.js",
    time: "3",
    details: "Details",
    star: "0",
    codeImage: snippetOne,
  },
  {
    id: 2,
    userImage: myselfImage,
    userName: "@basudevkumer",
    to: "https://github.com/basudevkumer/e-commerce1.0/blob/main/src/hooks/useCategory.jsx",
    time: "3",
    details: "Details",
    star: "0",
    codeImage: snippetTwo,
  },
];
const allProjects = [
  {
    id: 1,
    title: "Project 1 ",
    subtitle: "// Cilcon E-Commerce Platform",
    image: projectImages[0].image,
    description:
      "A modern e-commerce web application with smooth UI interactions.\nFocused on performance, state management, and reusable components.",
    technologies: [
      "React",
      "CSS",
      "Tailwind",
      "HTML",
      "tanstack",
      "tanstack-qerry",
      "swiper js",
      "redux",
      "firebase",
      "react-router",
      "JavaScript",
    ],
    to: "https://e-commerce1-0.vercel.app/",
    mainTect: techIcons[0].icon,
  },
  {
    id: 2,
    title: "Project 2 ",
    subtitle: "// Innovate Landing Page – Version 1 (Animated)",
    image: projectImages[1].image,
    description:
      "An animated landing page showcasing creative UI transitions.\nBuilt to explore motion effects and interactive design patterns.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "react-bootstrap",
      "animation",
      "keyfram",
      "JavaScript",
    ],
    to: "https://react-innovale-one.vercel.app/",
    mainTect: techIcons[7].icon,
  },
  {
    id: 3,
    title: "Project 3 ",
    subtitle: "// Innovate Landing Page – Version 2 (Animated)",
    image: projectImages[2].image,
    description:
      "A visually engaging animated website with dynamic elements.\nEmphasizes smooth transitions and responsive layouts.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "react-bootstrap",
      "animation",
      "keyfram",
      "JavaScript",
    ],
    to: "https://innovale2.vercel.app/",
    mainTect: techIcons[7].icon,
  },
  {
    id: 4,
    title: "Project 4 ",
    subtitle: "// Blockchain Product Landing Page",
    image: projectImages[9].image,
    description:
      "A clean and modern blockchain-themed landing page design.\nCreated to practice layout composition and Tailwind styling.",
    technologies: ["HTML", "CSS", "tailwind", "tailwind-cli"],
    to: "https://blockchain-xi-henna.vercel.app/",
    mainTect: techIcons[2].icon,
  },
  {
    id: 5,
    title: "Project 5 ",
    subtitle: "// Innovate Landing Page – Version 4",
    image: projectImages[4].image,
    description:
      "A responsive landing page with engaging UI components.\nFocused on reusable sections and user-friendly structure.",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "react",
      "react-slick",
      "tailwindcss",
      "react-router",
    ],
    to: "https://innovate5.vercel.app/",
    mainTect: techIcons[0].icon,
  },
  {
    id: 6,
    title: "Project 6 ",
    subtitle: "// Foodi Product Landing Experience",
    image: projectImages[5].image,
    description:
      "A food-themed landing page highlighting visual appeal.\nDesigned to experiment with sliders and modern UI spacing.",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "swiper",
      "react-router",
      "tailwindcss",
      "react",
    ],
    to: "https://foodi-zeta-livid.vercel.app/",
   mainTect: techIcons[0].icon,
  },
  {
    id: 7,
    title: "Project 7 ",
    subtitle: "// Finsweet-Inspired Multi-Page Website",
    image: projectImages[6].image,
    description:
      "A multi-section website inspired by real-world layouts.\nBuilt to improve component structuring and UI consistency.",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "swiper",
      "react-router",
      "bootstrap",
      "react-bootstrap",
      "react-slick",
      "aos",
    ],
    to: "https://react-finsweet-two.vercel.app/",
    mainTect: techIcons[7].icon,
  },
  {
    id: 8,
    title: "Project 8 ",
    subtitle: "// FreshWebsite Minimal Landing Page",
    image: projectImages[7].image,
    description:
      "A simple yet elegant landing page design concept.\nFocused on clean layout and basic styling techniques.",
    technologies: ["HTML", "CSS"],
    to: "https://basudevkumer.github.io/freshWebsite/",
    mainTect: techIcons[1].icon,
  },
  {
    id: 9,
    title: "Project 9 ",
    subtitle: "// Dazzling UI Demo Website",
    image: projectImages[8].image,
    description:
      "A demo website built for layout and styling practice.\nExplores Bootstrap components and responsive behavior.",
    technologies: ["HTML", "CSS", "bootstrap"],
    to: "https://basudevkumer.github.io/Boot_Project_1/",
    mainTect: techIcons[3].icon,
  },
  {
    id: 10,
    title: "Project 10 ",
    subtitle: "// Innovate Landing Page – Version 3",
    image: projectImages[3].image,
    description:
      "A modern landing page featuring interactive UI elements.\nDesigned to test design systems and component reuse.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "daisyui",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innvate4.vercel.app/",
    mainTect: techIcons[0].icon,
  },
  {
    id: 11,
    title: "Project 11 ",
    subtitle: "// Innovate Landing Page – Version 5",
    image: projectImages[10].image,
    description:
      "A lightweight landing page project with structured layout.\nBuilt to refine styling and responsive alignment skills.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://github.com/basudevkumer/innovate5",
     mainTect: techIcons[0].icon,
  },
  {
    id: 12,
    title: "Project 12 ",
    subtitle: "// Innovate Landing Page – Version 6",
    image: projectImages[11].image,
    description:
      "A modern UI-focused landing page with motion effects.\nHighlights component-based design and visual hierarchy.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
      "motion",
      "flowbite-react",
    ],
    to: "https://innovate6.vercel.app/",
    mainTect: techIcons[0].icon,
  },
  {
    id: 13,
    title: "Project 13 ",
    subtitle: "// Innovate Landing Page – Version 7",
    image: projectImages[12].image,
    description:
      "A clean Bootstrap-based landing page layout experiment.\nFocused on grid usage and visual balance.",
    technologies: ["HTML", "CSS", "bootstrap"],
    to: "https://innovate7.vercel.app/",
     mainTect: techIcons[3].icon,
  },
  {
    id: 14,
    title: "Project 14 ",
    subtitle: "// Innovate Landing Page – Version 8",
    image: projectImages[13].image,
    description:
      "A polished landing page with responsive UI sections.\nBuilt to practice layout refinement and spacing control.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innovate8-seven.vercel.app/",
     mainTect: techIcons[0].icon,
  },
  {
    id: 15,
    title: "Project 15 ",
    subtitle: "// Innovate Landing Page – Version 9",
    image: projectImages[14].image,
    description:
      "A modern landing page exploring reusable UI patterns.\nDesigned for improving component-driven development.",
    technologies: [
      "HTML",
      "CSS",
      "react",
      "react-slick",
      "tailwind",
      "JavaScript",
    ],
    to: "https://innovate9.vercel.app/",
     mainTect: techIcons[0].icon,
  },
  {
    id: 16,
    title: "Project 16 ",
    subtitle: "// Interactive Carousel UI Component",
    image: projectImages[15].image,
    description:
      "A simple carousel-based UI interaction project.\nCreated to understand animations and sliding behavior.",
    technologies: ["HTML", "CSS", "tailwind", "JavaScript"],
    to: "https://caurosel.vercel.app/",
     mainTect: techIcons[4].icon,
  },
  {
    id: 17,
    title: "Project 17 ",
    subtitle: "// Dynamic Quiz Application",
    image: projectImages[16].image,
    description:
      "A basic quiz application with dynamic question flow.\nFocused on logic handling and DOM interactions.",
    technologies: ["HTML", "CSS", "tailwind", "JavaScript"],
    to: "https://simple-quiz-app-qo7i.vercel.app/",
    mainTect: techIcons[4].icon,
  },
  {
    id: 18,
    title: "Project 18 ",
    subtitle: "// Toast Notification UI System",
    image: projectImages[17].image,
    description:
      "A toast notification UI experiment for user feedback.\nBuilt to practice event-driven interactions and timing.",
    technologies: ["HTML", "CSS", "bootstrap", "JavaScript"],
    to: "https://basudevkumer.github.io/Toast-js/",
     mainTect: techIcons[4].icon,
  },
];

const allTechIcons = [
  {
    id: 1,
    name: "React",
    icon: techIcons[0].icon,
  },
  {
    id: 2,
    name: "HTML",
    icon: techIcons[1].icon,
  },

  { id: 3, name: "Tailwind", icon: techIcons[2].icon },
  {
    id: 4,
    name: "Bootstrap",
    icon: techIcons[3].icon,
  },
  { id: 5, name: "Javascript", icon: techIcons[4].icon },
  { id: 6, name: "Next js", icon: techIcons[5].icon },
  { id: 7, name: "Typescript", icon: techIcons[6].icon },
  { id: 8, name: "React-Bootstrap", icon: techIcons[7].icon },
];

const aboutTitle = [
  { id: 1, icon: aboutPageIcon[0].icon, title: "professional-info" },
  { id: 2, icon: aboutPageIcon[1].icon, title: "personal-info" },
  { id: 3, icon: aboutPageIcon[2].icon, title: "hobbies-info" },
];

const aboutobj = [
  { id: 1, title: "personal-info" },
  { id: 2, title: "professional-info" },
  { id: 3, title: "hobbies" },
  { id: 4, title: "contacts" },
];

export {
  navbarArray,
  footerArray,
  bio,
  contact,
  snippet,
  professionalInfo,
  hobbies,
  aboutTitle,
  allProjects,
  allTechIcons,
  aboutobj,
};
